version: '3.7'

services:

  nginx:
    restart: always
    build:
      context: ./web-server
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - bridge_network
    depends_on:
      - ecommerce-app1
      - ecommerce-app2

  ecommerce-app1:
    build:
      context: ./back/ecommerce
      dockerfile: Dockerfile
    ports:
      - "8080:8080" #"HOST_PORT:CONTAINER_PORT"
    networks:
      - bridge_network
    environment:
      - SERVER_PORT=8080

  ecommerce-app2:
    build:
      context: ./back/ecommerce
      dockerfile: Dockerfile
    ports:
      - "8081:8080" #"HOST_PORT:CONTAINER_PORT"
    networks:
      - bridge_network
    environment:
      - SERVER_PORT=8081

networks:
  bridge_network: #얘로 frontend, backend, db 같은 네트워크로 묶는 것
    driver: bridge
