spring:
  config:
    import:
      - classpath:/application-local.yml
      - classpath:/application-test.yml
      - classpath:/application-docker.yml
      - classpath:/application-prod.yml
  profiles:
    default: local