server:
  port: ${SERVER_PORT:8080}
  #  port: 8081
  servlet:
    session:
      timeout: 30m  # 30 minutes
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/ecommerce-database?autoReconnect=true&serverTimezone=Asia/Seoul&rewriteBatchedStatements=true
    username: user123
    password: user123
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl_auto: create
    properties.hibernate:
      format_sql: true
      show-sql: true
      #      generate_statistics: true
      open-in-view: false # TODO - OIV 자세히 알아보기. log level: WARNING - spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering.
      default_batch_fetch_size: 1000
      jdbc:
        batch_size: 1000
  batch:
    initialize-schema: always
    job:
      enabled: false #true로 하면 @Bean으로 등록된 cron batch steps들이 시작과 동시에 자동 실행되니까 false로 꺼둔다.
  redis:
    host: redis
    port: 6379
  session:
    store-type: redis
    timeout: 60m

logging:
  level:
    #    root: DEBUG
    org:
      hibernate:
        SQL: debug
        type: trace
      springframework:
        security: DEBUG
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true


